// Realistic seed data matching the PostgreSQL seed architecture

export const MOCK_CATEGORIES = [
  { id: 'cat-1', name: 'Sedan', code: 'SED', description: 'Standard 4-door passenger sedans' },
  { id: 'cat-2', name: 'SUV & Crossover', code: 'SUV', description: 'Sport Utility Vehicles and compact crossovers' },
  { id: 'cat-3', name: 'Luxury & Executive', code: 'LUX', description: 'Premium luxury and executive vehicles' },
  { id: 'cat-4', name: 'Electric & EV', code: 'EV', description: 'Pure electric vehicles with specialized acoustic glass' },
  { id: 'cat-5', name: 'Commercial & Vans', code: 'COM', description: 'Light commercial, delivery vans, and fleet vehicles' }
];

export const MOCK_BRANDS = [
  { id: 'b-1', categoryId: 'cat-1', name: 'Toyota', country: 'Japan', code: 'TOY' },
  { id: 'b-2', categoryId: 'cat-1', name: 'Honda', country: 'Japan', code: 'HON' },
  { id: 'b-3', categoryId: 'cat-3', name: 'BMW', country: 'Germany', code: 'BMW' },
  { id: 'b-4', categoryId: 'cat-2', name: 'Ford', country: 'USA', code: 'FRD' },
  { id: 'b-5', categoryId: 'cat-2', name: 'Hyundai', country: 'South Korea', code: 'HYU' },
  { id: 'b-6', categoryId: 'cat-4', name: 'Tesla', country: 'USA', code: 'TSL' }
];

export const MOCK_MODELS = [
  { id: 'm-1', brandId: 'b-1', name: 'Camry', yearStart: 2018, yearEnd: 2025, bodyType: 'Sedan' },
  { id: 'm-2', brandId: 'b-1', name: 'RAV4', yearStart: 2019, yearEnd: 2025, bodyType: 'SUV' },
  { id: 'm-3', brandId: 'b-2', name: 'Civic', yearStart: 2016, yearEnd: 2025, bodyType: 'Sedan' },
  { id: 'm-4', brandId: 'b-2', name: 'CR-V', yearStart: 2017, yearEnd: 2025, bodyType: 'SUV' },
  { id: 'm-5', brandId: 'b-3', name: '3 Series (G20)', yearStart: 2019, yearEnd: 2025, bodyType: 'Executive Sedan' },
  { id: 'm-6', brandId: 'b-4', name: 'Explorer', yearStart: 2020, yearEnd: 2025, bodyType: 'Mid-size SUV' },
  { id: 'm-7', brandId: 'b-5', name: 'Tucson', yearStart: 2021, yearEnd: 2025, bodyType: 'Compact SUV' },
  { id: 'm-8', brandId: 'b-6', name: 'Model 3', yearStart: 2017, yearEnd: 2025, bodyType: 'Fastback Sedan' }
];

export const MOCK_VARIANTS = [
  { id: 'v-1', modelId: 'm-1', name: 'LE / SE 2.5L Gas', year: '2018-2024', trim: 'Standard ADAS' },
  { id: 'v-2', modelId: 'm-1', name: 'XLE / XSE Hybrid w/ HUD', year: '2021-2025', trim: 'Acoustic HUD' },
  { id: 'v-3', modelId: 'm-2', name: 'XLE / Limited AWD', year: '2019-2024', trim: 'Rain Sensor + Camera' },
  { id: 'v-4', modelId: 'm-3', name: 'Sport / Touring 1.5T', year: '2022-2025', trim: 'Honda Sensing ADAS' },
  { id: 'v-5', modelId: 'm-4', name: 'EX-L / Sport Touring Hybrid', year: '2023-2025', trim: 'Heated Wiper Park' },
  { id: 'v-6', modelId: 'm-5', name: '330i / M340i xDrive', year: '2020-2025', trim: 'HUD + ConnectedDrive' },
  { id: 'v-7', modelId: 'm-6', name: 'XLT / Timberline 4WD', year: '2021-2025', trim: 'Co-Pilot360 Assist' },
  { id: 'v-8', modelId: 'm-7', name: 'SEL / N Line / Limited', year: '2022-2025', trim: 'SmartSense ADAS' },
  { id: 'v-9', modelId: 'm-8', name: 'Long Range / Performance', year: '2021-2025', trim: 'Acoustic Glass + Autopilot' }
];

export const GLASS_POSITIONS = [
  { id: 'front_windshield', label: 'Front Windshield', short: 'Windshield', icon: 'Shield' },
  { id: 'rear_windshield', label: 'Rear Windshield (Backlite)', short: 'Rear Backlite', icon: 'Car' },
  { id: 'front_left_door', label: 'Front Left Door Glass', short: 'FL Door', icon: 'Square' },
  { id: 'front_right_door', label: 'Front Right Door Glass', short: 'FR Door', icon: 'Square' },
  { id: 'rear_left_door', label: 'Rear Left Door Glass', short: 'RL Door', icon: 'Square' },
  { id: 'rear_right_door', label: 'Rear Right Door Glass', short: 'RR Door', icon: 'Square' },
  { id: 'left_quarter', label: 'Left Quarter Vent Glass', short: 'L Quarter', icon: 'Layers' },
  { id: 'right_quarter', label: 'Right Quarter Vent Glass', short: 'R Quarter', icon: 'Layers' },
  { id: 'sunroof', label: 'Panoramic Sunroof / Roof Glass', short: 'Sunroof', icon: 'Sun' }
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    sku: 'FW04892-GTY',
    partNumber: '56101-06901',
    name: 'Acoustic Solar Windshield w/ ADAS Camera & Rain Sensor',
    brandName: 'Toyota',
    modelName: 'Camry',
    variantName: 'XLE / XSE Hybrid w/ HUD (2021-2025)',
    categoryId: 'cat-1',
    brandId: 'b-1',
    modelId: 'm-1',
    variantId: 'v-2',
    glassPosition: 'front_windshield',
    unitPrice: 420.00,
    costPrice: 245.00,
    stockCount: 8,
    minThreshold: 3,
    tintColor: 'Green Solar Tint',
    features: ['Acoustic Interlayer', 'ADAS Bracket', 'Rain Sensor', 'HUD Compatible'],
    oemSupplier: 'Asahi Glass (AGC)',
    lastRestocked: '2026-09-28'
  },
  {
    id: 'prod-2',
    sku: 'FW04210-GTY',
    partNumber: '56101-06780',
    name: 'Front Windshield w/ Safety Sense ADAS Bracket',
    brandName: 'Toyota',
    modelName: 'Camry',
    variantName: 'LE / SE 2.5L Gas (2018-2024)',
    categoryId: 'cat-1',
    brandId: 'b-1',
    modelId: 'm-1',
    variantId: 'v-1',
    glassPosition: 'front_windshield',
    unitPrice: 310.00,
    costPrice: 180.00,
    stockCount: 12,
    minThreshold: 4,
    tintColor: 'Green Solar Tint',
    features: ['ADAS Bracket', 'Third Visor Frit'],
    oemSupplier: 'Pilkington',
    lastRestocked: '2026-10-02'
  },
  {
    id: 'prod-3',
    sku: 'RW03980-HTY',
    partNumber: '64801-06390',
    name: 'Heated Rear Windshield w/ Integrated Antenna & Privacy Tint',
    brandName: 'Toyota',
    modelName: 'Camry',
    variantName: 'LE / SE 2.5L Gas (2018-2024)',
    categoryId: 'cat-1',
    brandId: 'b-1',
    modelId: 'm-1',
    variantId: 'v-1',
    glassPosition: 'rear_windshield',
    unitPrice: 280.00,
    costPrice: 160.00,
    stockCount: 2,
    minThreshold: 3,
    tintColor: 'Dark Privacy Smoke',
    features: ['Heated Defroster Grid', 'AM/FM Glass Antenna'],
    oemSupplier: 'Fuyao Glass',
    lastRestocked: '2026-09-15'
  },
  {
    id: 'prod-4',
    sku: 'FW05120-GHN',
    partNumber: '73111-T20-A11',
    name: 'Acoustic Windshield w/ Honda Sensing Dual Cam Bracket',
    brandName: 'Honda',
    modelName: 'Civic',
    variantName: 'Sport / Touring 1.5T (2022-2025)',
    categoryId: 'cat-1',
    brandId: 'b-2',
    modelId: 'm-3',
    variantId: 'v-4',
    glassPosition: 'front_windshield',
    unitPrice: 385.00,
    costPrice: 215.00,
    stockCount: 1,
    minThreshold: 3,
    tintColor: 'Solar Green',
    features: ['Acoustic Core', 'Honda Sensing Bracket', 'Rain Sensor Gel Pack'],
    oemSupplier: 'Saint-Gobain Sekurit',
    lastRestocked: '2026-09-10'
  },
  {
    id: 'prod-5',
    sku: 'FW05834-BMW',
    partNumber: '51317498532',
    name: 'Climate Comfort Windshield w/ HUD & Driving Assistant Pro',
    brandName: 'BMW',
    modelName: '3 Series (G20)',
    variantName: '330i / M340i xDrive (2020-2025)',
    categoryId: 'cat-3',
    brandId: 'b-3',
    modelId: 'm-5',
    variantId: 'v-6',
    glassPosition: 'front_windshield',
    unitPrice: 690.00,
    costPrice: 420.00,
    stockCount: 4,
    minThreshold: 2,
    tintColor: 'Infrared Reflective Violet Tint',
    features: ['IR Reflective', 'Acoustic', 'HUD Wedge', 'KAFAS ADAS Bracket', 'Heated Wiper Area'],
    oemSupplier: 'Saint-Gobain Sekurit',
    lastRestocked: '2026-09-25'
  },
  {
    id: 'prod-6',
    sku: 'FD02410-TSL',
    partNumber: '1072583-00-H',
    name: 'Front Left Driver Acoustic Laminated Door Glass',
    brandName: 'Tesla',
    modelName: 'Model 3',
    variantName: 'Long Range / Performance (2021-2025)',
    categoryId: 'cat-4',
    brandId: 'b-6',
    modelId: 'm-8',
    variantId: 'v-9',
    glassPosition: 'front_left_door',
    unitPrice: 240.00,
    costPrice: 135.00,
    stockCount: 0,
    minThreshold: 2,
    tintColor: 'Clear Solar Acoustic',
    features: ['Double-pane Laminated Acoustic', 'Frameless Edge Grind'],
    oemSupplier: 'AGP Glass',
    lastRestocked: '2026-08-30'
  },
  {
    id: 'prod-7',
    sku: 'SR01099-TSL',
    partNumber: '1083428-00-J',
    name: 'Electro-Tinted UV Panoramic Roof Glass Assembly',
    brandName: 'Tesla',
    modelName: 'Model 3',
    variantName: 'Long Range / Performance (2021-2025)',
    categoryId: 'cat-4',
    brandId: 'b-6',
    modelId: 'm-8',
    variantId: 'v-9',
    glassPosition: 'sunroof',
    unitPrice: 850.00,
    costPrice: 560.00,
    stockCount: 3,
    minThreshold: 1,
    tintColor: 'Ultra Deep UV/IR Silver Tint',
    features: ['99.9% UV Rejection', 'Tempered Solar Laminated'],
    oemSupplier: 'Saint-Gobain Sekurit',
    lastRestocked: '2026-10-01'
  },
  {
    id: 'prod-8',
    sku: 'FW05401-FRD',
    partNumber: 'LB5Z-7803100-B',
    name: 'Acoustic Windshield w/ Co-Pilot360 ADAS & Wiper De-icer',
    brandName: 'Ford',
    modelName: 'Explorer',
    variantName: 'XLT / Timberline 4WD (2021-2025)',
    categoryId: 'cat-2',
    brandId: 'b-4',
    modelId: 'm-6',
    variantId: 'v-7',
    glassPosition: 'front_windshield',
    unitPrice: 460.00,
    costPrice: 280.00,
    stockCount: 6,
    minThreshold: 2,
    tintColor: 'Green Solar',
    features: ['SoundScreen Acoustic', 'Full Grid Wiper De-Icer', 'Lane Keep Camera'],
    oemSupplier: 'Carlex Glass',
    lastRestocked: '2026-09-20'
  }
];

export const MOCK_USERS = [
  { id: 'usr-1', name: 'Admin User', email: 'admin@glasspos.com', role: 'ADMIN', status: 'ACTIVE', lastLogin: 'Just now' },
  { id: 'usr-2', name: 'John Doe (Staff 1)', email: 'staff1@glasspos.com', role: 'STAFF', status: 'ACTIVE', lastLogin: '2 hours ago' },
  { id: 'usr-3', name: 'Sarah Connor (Staff 2)', email: 'staff2@glasspos.com', role: 'STAFF', status: 'ACTIVE', lastLogin: 'Yesterday' },
  { id: 'usr-4', name: 'Mike Vance (Staff 3)', email: 'staff3@glasspos.com', role: 'STAFF', status: 'ACTIVE', lastLogin: '3 days ago' }
];
